// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppiAPIDOTNET.Data;

#nullable disable

namespace ShoppiAPIDOTNET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShoppiAPIDOTNET.Data.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("UserStatus")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("46bb231d-6b09-4797-a5d7-5eb7c5adf01e"),
                            CreatedAt = new DateTime(2024, 1, 18, 20, 8, 15, 811, DateTimeKind.Local).AddTicks(2878),
                            Email = "kevinv@example.com",
                            LastUpdatedAt = new DateTime(2024, 1, 18, 20, 8, 15, 811, DateTimeKind.Local).AddTicks(2897),
                            PasswordHash = "$2a$11$QGbqhRgG5xwaxMk2i8xb4edMQAYVYkMuyfAPapCDnpDsrsOd5V1sW",
                            UserName = "KevinV",
                            UserProfileId = -1,
                            UserStatus = 0,
                            UserTypeId = -1
                        },
                        new
                        {
                            Id = new Guid("573a75fa-2106-42d3-958f-65829ca5608e"),
                            CreatedAt = new DateTime(2024, 1, 18, 20, 8, 15, 811, DateTimeKind.Local).AddTicks(2902),
                            Email = "luisd@example.com",
                            LastUpdatedAt = new DateTime(2024, 1, 18, 20, 8, 15, 811, DateTimeKind.Local).AddTicks(2904),
                            PasswordHash = "$2a$11$GLY5Baw4A1lYtuPL.wS1c.vRoAJ6V.hIL9DNwD1tbOSWF2tQjfMg6",
                            UserName = "LuisF",
                            UserProfileId = -2,
                            UserStatus = 0,
                            UserTypeId = -2
                        });
                });

            modelBuilder.Entity("ShoppiAPIDOTNET.Data.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LastName")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            LastName = "Villalobos",
                            Name = "Kevin",
                            PhoneNumber = "+5212323121212"
                        },
                        new
                        {
                            Id = -2,
                            LastName = "Fonsi",
                            Name = "Luis",
                            PhoneNumber = "+5212312341234"
                        });
                });

            modelBuilder.Entity("ShoppiAPIDOTNET.Data.Models.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Administrador del sistema",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = -2,
                            Description = "Usuario con permiso de publicar anuncios",
                            Name = "Seller"
                        });
                });

            modelBuilder.Entity("ShoppiAPIDOTNET.Data.Models.UserAccount", b =>
                {
                    b.HasOne("ShoppiAPIDOTNET.Data.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppiAPIDOTNET.Data.Models.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");

                    b.Navigation("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
